import { Button } from '@/ui/shadcn/button';
import { Switch } from '@/ui/shadcn/switch';

import { Field, SettingsGroup } from '../SettingsField';
import { SettingsTabContent } from '../SettingsViewParts';

export function SettingsMediaTab({ media }: any) {
    const {
        prefs,
        onScreenshotHelperChange,
        onScreenshotHelperModifyFilenameChange,
        onScreenshotHelperCopyToClipboardChange,
        onDeleteAllScreenshotMetadata,
        onOpenUgcPhotosFolder,
        onOpenUgcFolderSelector,
        onResetUgcFolder,
        onSaveInstancePrintsChange,
        onCropInstancePrintsChange,
        onSaveInstanceStickersChange,
        onSaveInstanceEmojiChange
    } = media;
    const { t } = useTranslation();
    return (
        <SettingsTabContent value="media">
            <SettingsGroup
                title={t(
                    'view.settings.advanced.advanced.screenshot_helper.header'
                )}
                description={t(
                    'view.settings.advanced.advanced.screenshot_helper.description'
                )}
            >
                <Field
                    label={t(
                        'view.settings.advanced.advanced.screenshot_helper.enable'
                    )}
                    description={t(
                        'view.settings.advanced.advanced.screenshot_helper.description_tooltip'
                    )}
                >
                    <Switch
                        checked={prefs.screenshotHelper}
                        onCheckedChange={onScreenshotHelperChange}
                    />
                </Field>
                <Field
                    label={t(
                        'view.settings.advanced.advanced.screenshot_helper.modify_filename'
                    )}
                    description={t(
                        'view.settings.advanced.advanced.screenshot_helper.modify_filename_tooltip'
                    )}
                >
                    <Switch
                        checked={prefs.screenshotHelperModifyFilename}
                        disabled={!prefs.screenshotHelper}
                        onCheckedChange={onScreenshotHelperModifyFilenameChange}
                    />
                </Field>
                <Field
                    label={t(
                        'view.settings.advanced.advanced.screenshot_helper.copy_to_clipboard'
                    )}
                >
                    <Switch
                        checked={prefs.screenshotHelperCopyToClipboard}
                        onCheckedChange={
                            onScreenshotHelperCopyToClipboardChange
                        }
                    />
                </Field>
                <Field
                    label={t(
                        'view.settings.advanced.advanced.delete_all_screenshot_metadata.button'
                    )}
                >
                    <Button
                        type="button"
                        variant="outline"
                        onClick={onDeleteAllScreenshotMetadata}
                    >
                        {t(
                            'view.settings.advanced.advanced.delete_all_screenshot_metadata.button'
                        )}
                    </Button>
                </Field>
            </SettingsGroup>
            <SettingsGroup
                title={t('view.settings.advanced.advanced.user_content.header')}
                description={t(
                    'view.settings.advanced.advanced.user_content.description'
                )}
            >
                <div className="flex flex-wrap gap-2">
                    <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={onOpenUgcPhotosFolder}
                    >
                        {t(
                            'view.settings.advanced.advanced.user_content.folder'
                        )}
                    </Button>
                    <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={onOpenUgcFolderSelector}
                    >
                        {t(
                            'view.settings.advanced.advanced.user_content.set_folder'
                        )}
                    </Button>
                    {prefs.userGeneratedContentPath ? (
                        <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={onResetUgcFolder}
                        >
                            {t(
                                'view.settings.advanced.advanced.user_content.reset_override'
                            )}
                        </Button>
                    ) : null}
                </div>
            </SettingsGroup>
            <SettingsGroup
                title={t(
                    'view.settings.advanced.advanced.save_instance_prints_to_file.header'
                )}
                description={t(
                    'view.settings.advanced.advanced.save_instance_prints_to_file.header_tooltip'
                )}
            >
                <Field
                    label={t(
                        'view.settings.advanced.advanced.save_instance_prints_to_file.description'
                    )}
                >
                    <Switch
                        checked={prefs.saveInstancePrints}
                        onCheckedChange={onSaveInstancePrintsChange}
                    />
                </Field>
                <Field
                    label={t(
                        'view.settings.advanced.advanced.save_instance_prints_to_file.crop'
                    )}
                >
                    <Switch
                        checked={prefs.cropInstancePrints}
                        disabled={!prefs.saveInstancePrints}
                        onCheckedChange={onCropInstancePrintsChange}
                    />
                </Field>
            </SettingsGroup>
            <SettingsGroup
                title={t(
                    'view.settings.advanced.advanced.save_instance_stickers_to_file.header'
                )}
            >
                <Field
                    label={t(
                        'view.settings.advanced.advanced.save_instance_stickers_to_file.description'
                    )}
                >
                    <Switch
                        checked={prefs.saveInstanceStickers}
                        onCheckedChange={onSaveInstanceStickersChange}
                    />
                </Field>
            </SettingsGroup>
            <SettingsGroup
                title={t(
                    'view.settings.advanced.advanced.save_instance_emoji_to_file.header'
                )}
                description={t(
                    'view.settings.advanced.advanced.save_instance_prints_to_file.header_tooltip'
                )}
            >
                <Field
                    label={t(
                        'view.settings.advanced.advanced.save_instance_emoji_to_file.description'
                    )}
                >
                    <Switch
                        checked={prefs.saveInstanceEmoji}
                        onCheckedChange={onSaveInstanceEmojiChange}
                    />
                </Field>
            </SettingsGroup>
        </SettingsTabContent>
    );
}
import { useTranslation } from 'react-i18next';
