import { EntityDialogTabs } from '../../EntityDialogScaffold.jsx';
import {
    UserDialogActivityTab,
    UserDialogAvatarsTab,
    UserDialogFavoriteWorldsTab,
    UserDialogInstanceHistoryTab,
    UserDialogJsonTab,
    UserDialogMutualTab,
    UserDialogWorldsTab
} from './UserDialogDataTabs.jsx';
import { UserDialogGroupsTab } from './UserDialogGroupsTab.jsx';
import { UserDialogInfoTab } from './UserDialogInfoTab.jsx';

export function UserDialogTabsSection({
    activeTab,
    avatarReleaseStatus,
    avatarSort,
    bioLinks,
    changeAvatarReleaseStatus,
    changeAvatarSort,
    changeTab,
    changeWorldOrder,
    changeWorldSort,
    currentAvatarDialogArgs,
    currentAvatarDisplayName,
    currentAvatarTarget,
    currentEndpoint,
    currentUserId,
    effectiveGroupSort,
    favoriteWorlds,
    filteredFavoriteWorlds,
    filteredMutualFriends,
    filteredProfileGroups,
    filteredProfileWorlds,
    groupActionId,
    groupEditMode,
    groupSearchActive,
    hideUserMemos,
    hideUserNotes,
    isCurrentUser,
    isFavorite,
    isFriend,
    lastSeen,
    loadTab,
    locationFriendCount,
    locationInstance,
    locationInstanceUsers,
    locationOwnerId,
    locationPlayerCount,
    locationWorldTitle,
    memo,
    moderationState,
    mutualFriends,
    mutualSort,
    onEditMemo,
    onOpenCurrentAvatar,
    onOpenInstanceHistory,
    onPreviousInstancesChange,
    onRefreshLocation,
    openAvatarDialog,
    openGroupDialog,
    ownGroupCountText,
    previousInstances,
    profile,
    profileAvatars,
    profileGroups,
    profileWorlds,
    remoteData,
    remoteErrors,
    remoteStatus,
    representedGroup,
    representedGroupStatus,
    search,
    selectedGroupCount,
    selectedGroupIds,
    selectedUserGroups,
    remainingGroupCountText,
    setGroupEditMode,
    setGroupSort,
    setMutualSort,
    setSearch,
    tabCounts = {},
    tabs,
    t,
    userGroupSections,
    userJoinCount,
    userTimeSpent,
    visibleHomeLocationTarget,
    visibleMutualFriends,
    visiblePresenceLocation,
    visibleProfileAvatars,
    worldOrder,
    worldSort,
    groupActions
}) {
    const tabsWithCounts = tabs
        .filter((tab) => !tab.hidden)
        .map((tab) => {
            const count = Number(tabCounts[tab.value] ?? 0);
            return count > 0
                ? {
                      ...tab,
                      label: (
                          <span className="inline-flex items-baseline gap-1.5">
                              <span>{tab.label}</span>
                              <span className="text-muted-foreground text-[11px] leading-none font-medium tabular-nums">
                                  {count}
                              </span>
                          </span>
                      )
                  }
                : tab;
        });

    return (
        <EntityDialogTabs
            value={activeTab}
            onValueChange={changeTab}
            tabs={tabsWithCounts}
        >
            <UserDialogInfoTab
                presence={{
                    visiblePresenceLocation,
                    locationInstance,
                    locationOwnerId,
                    locationPlayerCount,
                    currentUserId,
                    currentEndpoint,
                    locationWorldTitle,
                    locationFriendCount,
                    previousInstances,
                    locationInstanceUsers
                }}
                presenceActions={{
                    onRefreshLocation,
                    onShowInstanceHistory: onOpenInstanceHistory
                }}
                onOpenInstanceHistory={onOpenInstanceHistory}
                profile={profile}
                hideUserNotes={hideUserNotes}
                onEditMemo={onEditMemo}
                memo={memo}
                hideUserMemos={hideUserMemos}
                currentAvatarTarget={currentAvatarTarget}
                currentAvatarDialogArgs={currentAvatarDialogArgs}
                currentAvatarDisplayName={currentAvatarDisplayName}
                openAvatarDialog={openAvatarDialog}
                representedGroupStatus={representedGroupStatus}
                representedGroup={representedGroup}
                openGroupDialog={openGroupDialog}
                bioLinks={bioLinks}
                isCurrentUser={isCurrentUser}
                lastSeen={lastSeen}
                userTimeSpent={userTimeSpent}
                userJoinCount={userJoinCount}
                visibleHomeLocationTarget={visibleHomeLocationTarget}
                t={t}
            />
            <UserDialogMutualTab
                mutualFriends={mutualFriends}
                filteredMutualFriends={filteredMutualFriends}
                visibleMutualFriends={visibleMutualFriends}
                remoteStatus={remoteStatus}
                remoteErrors={remoteErrors}
                loadTab={loadTab}
                search={search}
                setSearch={setSearch}
                mutualSort={mutualSort}
                setMutualSort={setMutualSort}
                t={t}
            />
            <UserDialogGroupsTab
                profileGroups={profileGroups}
                filteredProfileGroups={filteredProfileGroups}
                remoteStatus={remoteStatus}
                remoteErrors={remoteErrors}
                loadTab={loadTab}
                search={search}
                setSearch={setSearch}
                groupEditMode={groupEditMode}
                effectiveGroupSort={effectiveGroupSort}
                setGroupSort={setGroupSort}
                isCurrentUser={isCurrentUser}
                groupActionId={groupActionId}
                setGroupEditMode={setGroupEditMode}
                clearSelectedGroups={groupActions.clearSelectedGroups}
                selectVisibleGroups={groupActions.selectVisibleGroups}
                selectedGroupCount={selectedGroupCount}
                changeSelectedGroupsVisibility={
                    groupActions.changeSelectedGroupsVisibility
                }
                exportUserGroups={groupActions.exportUserGroups}
                selectedUserGroups={selectedUserGroups}
                leaveSelectedGroups={groupActions.leaveSelectedGroups}
                groupSearchActive={groupSearchActive}
                selectedGroupIds={selectedGroupIds}
                changeGroupVisibility={groupActions.changeGroupVisibility}
                leaveUserGroup={groupActions.leaveUserGroup}
                moveGroupInGameOrder={groupActions.moveGroupInGameOrder}
                setGroupSelected={groupActions.setGroupSelected}
                userGroupSections={userGroupSections}
                ownGroupCountText={ownGroupCountText}
                remainingGroupCountText={remainingGroupCountText}
                t={t}
            />
            <UserDialogWorldsTab
                filteredProfileWorlds={filteredProfileWorlds}
                profileWorlds={profileWorlds}
                remoteStatus={remoteStatus}
                remoteErrors={remoteErrors}
                loadTab={loadTab}
                search={search}
                setSearch={setSearch}
                worldSort={worldSort}
                changeWorldSort={changeWorldSort}
                worldOrder={worldOrder}
                changeWorldOrder={changeWorldOrder}
                t={t}
            />
            <UserDialogFavoriteWorldsTab
                remoteData={remoteData}
                favoriteWorlds={favoriteWorlds}
                filteredFavoriteWorlds={filteredFavoriteWorlds}
                remoteStatus={remoteStatus}
                remoteErrors={remoteErrors}
                loadTab={loadTab}
                search={search}
                setSearch={setSearch}
                t={t}
            />
            <UserDialogAvatarsTab
                currentAvatarTarget={currentAvatarTarget}
                currentAvatarDisplayName={currentAvatarDisplayName}
                onOpenCurrentAvatar={onOpenCurrentAvatar}
                visibleProfileAvatars={visibleProfileAvatars}
                profileAvatars={profileAvatars}
                remoteStatus={remoteStatus}
                remoteErrors={remoteErrors}
                loadTab={loadTab}
                search={search}
                setSearch={setSearch}
                profile={profile}
                currentUserId={currentUserId}
                avatarSort={avatarSort}
                changeAvatarSort={changeAvatarSort}
                avatarReleaseStatus={avatarReleaseStatus}
                changeAvatarReleaseStatus={changeAvatarReleaseStatus}
                t={t}
            />
            <UserDialogInstanceHistoryTab
                title={t('dialog.previous_instances.header')}
                backLabel={t('dialog.user.info.header')}
                previousInstances={previousInstances}
                profile={profile}
                onBack={!isCurrentUser ? () => changeTab('info') : null}
                onPreviousInstancesChange={onPreviousInstancesChange}
            />
            <UserDialogActivityTab
                profile={profile}
                isCurrentUser={isCurrentUser}
                active={activeTab === 'activity'}
            />
            <UserDialogJsonTab
                profile={profile}
                memo={memo}
                moderationState={moderationState}
                isFriend={isFriend}
                isFavorite={isFavorite}
            />
        </EntityDialogTabs>
    );
}
